// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcUe-r8JHenrooQoUAEnQc4PDhEKHfkaE',
    appId: '1:616236467109:web:83d26224bb51f79c911e4c',
    messagingSenderId: '616236467109',
    projectId: 'tugas-besar-motion',
    authDomain: 'tugas-besar-motion.firebaseapp.com',
    storageBucket: 'tugas-besar-motion.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqasUa2Yh0x0HcnR-wzQkI-7UgsjnBwE4',
    appId: '1:616236467109:android:77927cdb15744981911e4c',
    messagingSenderId: '616236467109',
    projectId: 'tugas-besar-motion',
    storageBucket: 'tugas-besar-motion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYg2U7zQj33il0OqS2C_9gtH5vBFb7HB4',
    appId: '1:616236467109:ios:54c45dc32ad6cf93911e4c',
    messagingSenderId: '616236467109',
    projectId: 'tugas-besar-motion',
    storageBucket: 'tugas-besar-motion.firebasestorage.app',
    iosBundleId: 'com.example.tugasBesarMotion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYg2U7zQj33il0OqS2C_9gtH5vBFb7HB4',
    appId: '1:616236467109:ios:54c45dc32ad6cf93911e4c',
    messagingSenderId: '616236467109',
    projectId: 'tugas-besar-motion',
    storageBucket: 'tugas-besar-motion.firebasestorage.app',
    iosBundleId: 'com.example.tugasBesarMotion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcUe-r8JHenrooQoUAEnQc4PDhEKHfkaE',
    appId: '1:616236467109:web:eb100731ff67a7ce911e4c',
    messagingSenderId: '616236467109',
    projectId: 'tugas-besar-motion',
    authDomain: 'tugas-besar-motion.firebaseapp.com',
    storageBucket: 'tugas-besar-motion.firebasestorage.app',
  );
}
